AllCops:
  TargetRubyVersion: 2.4.5

Layout/DotPosition:
  EnforcedStyle: leading

Metrics/AbcSize:
  Enabled: false
  Max: 25

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/LineLength:
  Max: 200

Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Naming/FileName:
  Enabled: false

Naming/HeredocDelimiterNaming:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/SignalException:
  EnforcedStyle: only_raise

Style/PercentLiteralDelimiters:
  Enabled: false

Style/TrailingCommaInArguments:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/ModuleFunction:
  Enabled: false

Style/NegatedIf:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/RegexpLiteral:
  EnforcedStyle: mixed
  AllowInnerSlashes: true

Style/SingleLineBlockParams:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  Enabled: true
  EnforcedStyleForMultiline: comma

Style/AndOr:
  Enabled: false

AllCops:
  Include:
    - Rakefile
    - config.ru
  Exclude:
    - db/**/*
    - config/**/*
    - script/**/*
    - app/views/**/*

Documentation:
  Enabled: false
