version: 2
jobs:
  test:
    parallelism: 1
    resource_class: medium
    working_directory: ~/halo
    docker:
    - image: node:10.16.3
    steps:
    - run:
        name: git checkout
        command: |
          mkdir -p ~/.ssh
          echo -e "Host github.com\n  StrictHostKeyChecking no" >> ~/.ssh/config
          if [ -z "$CIRCLE_BRANCH" ]; then
            git clone git@github.com:venturehacks/$CIRCLE_PROJECT_REPONAME.git .
          else
            git clone git@github.com:venturehacks/$CIRCLE_PROJECT_REPONAME.git . \
                --branch $CIRCLE_BRANCH --depth=100
          fi
          git reset --hard $CIRCLE_SHA1
    - run:
        name: yarn install
        command: yarn install
    - save_cache:
        name: Save yarn install cache
        key: v1-halo-node_modules-{{ checksum "yarn.lock" }}
        paths:
        - node_modules
    - run:
        name: build node module
        no_output_timeout: 1h
        command: yarn build:node
        environment:
          NODE_ENV: production
    - run:
        name: Tests
        command: yarn test
    - store_artifacts:
        path: log/test.log
    - store_test_results:
        path: test/reports

workflows:
  version: 2
  build-and-test:
    jobs:
    - test:
        context: org-global

# notify:
#   webhooks:
#   - url: https://angellist-deploy-bot.herokuapp.com/webhook/a3fde4eae0ab6cb52fcc02f5dcabf791
